#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/scripts/runtime-env.sh"
CONCURRENCY="${CONCURRENCY:-20}"
SEED_CONCURRENCY="${SEED_CONCURRENCY:-20}"
PAYLOAD_BYTES="${PAYLOAD_BYTES:-4096}"
TASKS="${TASKS:-10}"
CHUNK_SIZE="${CHUNK_SIZE:-65536}"
DB_MAX_CONNS="${DB_MAX_CONNS:-32}"
DB_MIN_CONNS="${DB_MIN_CONNS:-4}"
LOAD_GLOBAL_TIMEOUT="${LOAD_GLOBAL_TIMEOUT:-90m}"
TRANSFER_BATCH_BYTES="${TRANSFER_BATCH_BYTES:-8388608}"
MATRIX="${MATRIX:-100 500 1000}"
for n in $MATRIX; do
  echo
  echo "================ LOAD ${n} ================"
  WORKLOADS="$n" CONCURRENCY="$CONCURRENCY" SEED_CONCURRENCY="$SEED_CONCURRENCY" \
    PAYLOAD_BYTES="$PAYLOAD_BYTES" TASKS="$TASKS" CHUNK_SIZE="$CHUNK_SIZE" TRANSFER_BATCH_BYTES="$TRANSFER_BATCH_BYTES" DB_MAX_CONNS="$DB_MAX_CONNS" DB_MIN_CONNS="$DB_MIN_CONNS" LOAD_GLOBAL_TIMEOUT="$LOAD_GLOBAL_TIMEOUT" \
    "$ROOT/scripts/load-test.sh"
done
